parameters:
    application.controller.default.class: Application\Controller\DefaultController

    application.controller.front.user.show.class: Application\Controller\Front\User\ShowController

    application.controller.admin.security.class: Application\Controller\Admin\SecurityController
    application.controller.admin.default.class: Application\Controller\Admin\DefaultController

    application.controller.admin.user.active.class: Application\Controller\Admin\User\ActiveController
    application.controller.admin.user.deactive.class: Application\Controller\Admin\User\DeactiveController

    application.controller.admin.user.lock.class: Application\Controller\Admin\User\LockController
    application.controller.admin.user.unlock.class: Application\Controller\Admin\User\UnlockController

    application.controller.admin.user.create.class: Application\Controller\Admin\User\CreateController
    application.controller.admin.user.create_form.class: Application\Controller\Admin\User\CreateFormController
    application.controller.admin.user.update_form.class: Application\Controller\Admin\User\UpdateFormController
    application.controller.admin.user.update_account.class: Application\Controller\Admin\User\UpdateAccountController
    application.controller.admin.user.update_password.class: Application\Controller\Admin\User\UpdatePasswordController

    application.controller.admin.user.list.class: Application\Controller\Admin\User\ListController
    application.controller.admin.user.remove.class: Application\Controller\Admin\User\RemoveController

services:
    application.controller.default:
        class: %application.controller.default.class%
        arguments: ["@templating"]

    application.controller.admin.security:
        class: %application.controller.admin.security.class%
        arguments: ["@templating", "@security.authentication_utils", "@black_user.application.form.login"]

    application.controller.admin.default:
        class: %application.controller.admin.default.class%
        arguments: ["@templating"]

    application.controller.admin.user.active:
        class: %application.controller.admin.user.active.class%
        arguments: ["@black_user.application.controller.active", "@router"]

    application.controller.admin.user.deactive:
        class: %application.controller.admin.user.deactive.class%
        arguments: ["@black_user.application.controller.deactive", "@router"]

    application.controller.admin.user.lock:
        class: %application.controller.admin.user.lock.class%
        arguments: ["@black_user.application.controller.lock", "@router"]

    application.controller.admin.user.unlock:
        class: %application.controller.admin.user.unlock.class%
        arguments: ["@black_user.application.controller.unlock", "@router"]

    application.controller.admin.user.create:
        class: %application.controller.admin.user.create.class%
        scope: request
        arguments: ["@black_user.application.controller.create", "@black_user.application.form.handler.create_account", "@router"]

    application.controller.admin.user.create_form:
        class: %application.controller.admin.user.create_form.class%
        arguments: ["@black_user.application.form.create_account", "@templating"]

    application.controller.admin.user.update_form:
        class: %application.controller.admin.user.update_form.class%
        arguments: ["@black_user.infrastructure.service.read", "@application.assembler.update_account", "@application.assembler.update_password", "@black_user.application.form.update_account", "@black_user.application.form.update_password", "@templating"]

    application.controller.admin.user.update_account:
        class: %application.controller.admin.user.update_account.class%
        scope: request
        arguments: ["@black_user.application.controller.update_account", "@black_user.application.form.handler.update_account", "@black_user.infrastructure.service.read", "@router"]

    application.controller.admin.user.update_password:
        class: %application.controller.admin.user.update_password.class%
        scope: request
        arguments: ["@black_user.application.controller.update_password", "@black_user.application.form.handler.update_password", "@black_user.infrastructure.service.read", "@router"]

    application.controller.admin.user.list:
        class: %application.controller.admin.user.list.class%
        arguments: ["@black_user.application.controller.list", "@templating"]

    application.controller.admin.user.remove:
        class: %application.controller.admin.user.remove.class%
        arguments: ["@black_user.application.controller.remove", "@router"]

    application.controller.front.user.show:
        class: %application.controller.front.user.show.class%
        arguments: ["@black_user.application.controller.show", "@templating", "@application.assembler.show_user"]

