parameters:
    application.infrastructure.provider.user.class: Infrastructure\Provider\UserProvider

services:
    application.provider: @application.infrastructure.provider.user

    application.infrastructure.provider.user:
        class: %application.infrastructure.provider.user.class%
        public: false
        arguments: ["@black_user.infrastructure.service.read", "@black_user.infrastructure.cqrs.handler.connect", "Domain\Model\User"]
