parameters:
    black_website.infrastructure.persistence.cqrs.write.class: Black\Website\Infrastructure\Persistence\CQRS\WriteRepository
    black_website.infrastructure.persistence.cqrs.read.class: Black\Website\Infrastructure\Persistence\CQRS\ReadRepository

    black_website.infrastructure.cqrs.handler.create_website.class: Black\Website\Infrastructure\CQRS\Handler\CreateWebsiteHandler
    black_website.infrastructure.cqrs.handler.active_website.class: Black\Website\Infrastructure\CQRS\Handler\ActiveWebsiteHandler
    black_website.infrastructure.cqrs.handler.disable_website.class: Black\Website\Infrastructure\CQRS\Handler\DisableWebsiteHandler

services:
    black_website.infrastructure.persistence.cqrs.write:
        class: "%black_website.infrastructure.persistence.cqrs.write.class%"
        arguments: ["@black_website.infrastructure.persistence"]

    black_website.infrastructure.persistence.cqrs.read:
        class: "%black_website.infrastructure.persistence.cqrs.read.class%"
        arguments: ["@black_website.infrastructure.persistence"]

    black_website.infrastructure.cqrs.handler.create_website:
        class: "%black_website.infrastructure.cqrs.handler.create_website.class%"
        arguments:
            - "@black_website.infrastructure.service.write"
            - "@black_website.infrastructure.persistence"
            - "@event_dispatcher"
        tags:
            - { name: black_cqrs.handler, command: "Black\Website\Infrastructure\CQRS\Command\CreateWebsiteCommand" }

    black_website.infrastructure.cqrs.handler.active_website:
        class: "%black_website.infrastructure.cqrs.handler.active_website.class%"
        arguments:
            - "@black_website.infrastructure.service.write"
            - "@event_dispatcher"
        tags:
            - { name: black_cqrs.handler, command: "Black\Website\Infrastructure\CQRS\Command\ActiveWebsiteCommand" }

    black_website.infrastructure.cqrs.handler.disable_website:
        class: "%black_website.infrastructure.cqrs.handler.disable_website.class%"
        arguments:
            - "@black_website.infrastructure.service.write"
            - "@event_dispatcher"
        tags:
            - { name: black_cqrs.handler, command: "Black\Website\Infrastructure\CQRS\Command\DisableWebsiteCommand" }
