admin_login:
    path:   /admin/login
    defaults:  { _controller: ApplicationBundle:Admin\Security:login }

admin_login_check:
    path:   /admin/login_check

admin_logout:
    path:   /admin/logout

application:
    resource: "@ApplicationBundle/Controller/"
    type:     annotation
    prefix:   /
