security:

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers:  [in_memory, main]

        in_memory:
            memory:
                users:
                    admin: { password: kitten, roles: 'ROLE_SUPER_ADMIN' }

        main:
            id: application.provider

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Domain\Model\User: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_firewall:
            pattern:    ^/admin/login$
            anonymous:  ~

        admin:
            pattern:    ^/admin
            form_login:
                username_parameter: "login[username]"
                password_parameter: "login[password]"
                csrf_parameter: "login[_token]"
                csrf_provider: form.csrf_provider
                intention: admin_authentication
                login_path: /admin/login
                check_path: /admin/login_check
            logout:
                path:   /admin/logout
                target: /admin
            switch_user:
                role: ROLE_ADMIN
                parameter: _barbatruc

    access_control:
        - { path: ^/efconnect, role: ROLE_USER }
        - { path: ^/elfinder, role: ROLE_USER }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
