---
- name: Install PHP
  apt: name={{ item }} state=present
  with_items:
    - nginx-full
    - php5-cli
    - php5-fpm
    - php5-mysqlnd
    - php5-curl
    - php5-mcrypt
    - php5-imagick
    - php5-xdebug
    - php5-intl
  tags: install
  run_once: true

- name: Configuration files
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: '20-xdebug.ini.j2', dest: '/etc/php5/mods-available/xdebug.ini' }
    - { src: 'php-cli.ini.j2', dest: '/etc/php5/cli/php.ini' }
    - { src: 'php-fpm.ini.j2', dest: '/etc/php5/fpm/php.ini' }
    - { src: 'www.conf.j2', dest: '/etc/php5/fpm/pool.d/www.conf' }
  notify:
    - restart php5-fpm
  tags: install
  run_once: true