---
- name: Node.js | setup
  shell: curl -sL https://deb.nodesource.com/setup | bash -
  tags: nodejs

- name: Node.js | Install nodejs and npm
  action: apt pkg={{ item }} state=installed
  tags: nodejs
  with_items:
    - nodejs
