parameters:
    app.application.responder.create_website.class: Application\Website\Responder\CreateWebsite
    app.application.responder.active_website.class: Application\Website\Responder\ActiveWebsite
    app.application.responder.disable_website.class: Application\Website\Responder\DisableWebsite
    app.application.responder.view_website.class: Application\Website\Responder\ViewWebsite

services:
    app.application.responder.create_website:
        class: "%app.application.responder.create_website.class%"

    app.application.responder.active_website:
        class: "%app.application.responder.active_website.class%"

    app.application.responder.disable_website:
        class: "%app.application.responder.disable_website.class%"

    app.application.responder.view_website:
        class: "%app.application.responder.view_website.class%"
        arguments:
            - "@black_website.application.specification.website_is_readable"
            - "@app.serializer.default"
