---
- name: Install Nginx
  apt: name={{ item }} state=present
  with_items:
    - nginx-full
  tags: install
  run_once: true

- name: Configuration files
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'nginx-default.j2', dest: '/etc/nginx/sites-available/default' }
  notify:
    - restart nginx
  tags: install
  run_once: true