---
- name: All hosts
  hosts: all
  pre_tasks:
    - name: Update Apt
      apt: update_cache=yes cache_valid_time=3600

- name: Vagrant only tasks
  hosts: vagrant
  sudo: yes
  roles:
    - vagrant
    - sources
    - git
    - ohmyzsh
    - postfix
    - dotdeb
    - composer
    - mariadb
    - nginx
    - nodejs
    - bower
    - gulp
    - less
    - starter
